[[language]]
name = "cpp"
language-servers = ["clangd"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[[language]]
name = "c"
language-servers = ["clangd"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
