[editor.inline-diagnostics]
# Show inline diagnostics when the cursor is on the line
cursor-line = "error" # Can also be "warning", "info", "hint", or "disable"

# Show inline diagnostics on other lines (not on the cursor line)
other-lines = "warning" # Can also be "warning", "info", "hint", or "disable"

[[language]]
name = "cpp"
language-servers = ["clangd"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[[language]]
name = "c"
language-servers = ["clangd"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
