bind r source-file ~/.config/tmux/tmux.conf \; display "tmux reloaded"

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Proper terminal support
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",tmux-256color:Tc,xterm-kitty:Tc"

# Faster escape
set -s escape-time 0

# Mouse
set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Split panes
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Start window index from 1
set -g base-index 1

# Start pane index from 1
setw -g pane-base-index 1

# Renumber windows sequentially when a window is closed
set-option -g renumber-windows on

set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on

# Styles
# gray_light="#D8DEE9"
# gray_medium="#11A1A1"
# gray_dark="#3B4252"
# green_soft="#A3BE8C"
# blue_muted="#81A1C1"
# cyan_soft="#88C0D0"
# catppuccin_mocha_darker="#333333"
# black="#000000"
#
# set -g status-left-length 100
# set -g status-style "fg=${gray_light},bg=${catppuccin_mocha_darker}"
# set -g status-left "#[fg=${green_soft},bold] #S #[fg=${blue_muted},nobold]  "
# set -g status-right ""
# set -g status-right "#[fg=${cyan_soft},bold]   #(whoami)@#H "
# set -g window-status-current-format "#[fg=${gray_light}]󰐾#I:#W"
# set -g message-style "fg=${gray_light},bg=${black},bold"
# set -g pane-border-style "fg=${green_soft}"
# set -g pane-active-border-style "fg=${green_soft}"

# Status bar position
set -g status-position top

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Session persistence
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# tmux theme config
set -g @plugin "wfxr/tmux-power"
set -g @tmux_power_theme "sky"
# set -g @tmux_power_theme "gold"
# set -g @tmux_power_theme "violet"
# set -g @tmux_power_theme "coral"
# set -g @tmux_power_theme "moon"

# Auto-save tmux sessions every 5 minutes
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @resurrect-processes 'nvim'

run '~/.tmux/plugins/tpm/tpm'
