$primary = rgb(b3989d)
$surface = rgb(211c1d)
$secondary = rgb(a58f8d)
$error = rgb(ff2d50)
$tertiary = rgb(a3968f)
$surface_lowest = rgb(110e0f)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
