shell=/usr/bin/zsh

font=Agave Nerd Font:size=16:style=Medium:antialias=true:autohint=true

[main]
include=/usr/share/foot/themes/dracula

initial-window-size-pixels=1500x900

selection-target=clipboard

[environment]
TIMG_PIXELATION=sixel
TERM=foot

[scrollback]
lines=999999

[cursor]
style=block

[mouse]
hide-when-typing=no

[colors-dark]
alpha=0.8
# foreground=D1B88E
# background=201b14
# flash=7f7f00
# flash-alpha=0.5

## Normal/regular colors (color palette 0-7)
# regular0=262626 #gray
# regular1=cc0000 #red
# regular2=42B63F # green
# regular3=DD9400 #yello
# regular4=DD9400 #yello
# regular5=bf78cf #purple
# regular6=74cd45 #blue-green
# regular7=D1B88E #yellow-white

## Bright colors (color palette 8-15)
# bright0=a79e67 #gray-green
# bright1=ef2929 # red
# bright2=8ae234 #green
# bright3=ead96b #yellow
# bright4=729fcf #blue
# bright5=ad7fa8 #pink
# bright6=ead96b #yellow
# bright7=eeeeec #light-yellow

