# font
font_family JetBrains Mono Nerd Font
# font_family UbuntuMono Nerd Font
# font_family Agave Nerd Font Mono
# font_family Monoid Nerd Font
# font_family Iosevka NFM
font_size 14
# bold_font no
disable_bold_text_with_bright_colors no
italic_font auto 
# bold_italic_font auto

# cursor
# cursor_shape beam
# cursor_trail 1
# cursor_blink_interval 0.5
# cursor_stop_blinking_after 1

background_opacity 0.9
dynamic_background_opacity yes

cursor_shape block
shell_integration no-cursor

url_style curly
remember_window_size no
# initial_window_width 640
# initial_window_height 480
sync_to_monitor no
scrollbar_handle_opacity 0.5
scrollbar_track_opacity 0.1
scrollbar_track_hover_opacity 0

# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
# END_KITTY_THEME

map ctrl+backspace send_text all \x17
