# font
# font_family JetBrains Mono Nerd Font
font_family FiraCode Nerd Font Mono
# font_family SauceCodeProNerdFontMono
# font_family MesloLGS Nerd Font Mono
# font_family Agave Nerd Font Mono
# font_family Iosevka NFM
disable_ligatures always
font_size 12
bold_font auto
italic_font auto 
bold_italic_font auto

shell /usr/bin/zsh

# cursor
cursor_shape beam
cursor_trail 1
cursor_blink_interval 0

background_opacity 0.9
# background_opacity 1
# background #080810
# dynamic_background_opacity yes

cursor_shape block
shell_integration no-cursor

url_style curly
remember_window_size no
# initial_window_width 640
# initial_window_height 480
# sync_to_monitor no
# scrollbar_handle_opacity 0.5
# scrollbar_track_opacity 0.1
# scrollbar_track_hover_opacity 0

# BEGIN_KITTY_THEME
# YsDark
include current-theme.conf
# END_KITTY_THEME

map ctrl+backspace send_text all \x17

